// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCawtle6G1fL_1gp8ohGwophie9oi_tWR8',
    appId: '1:244411266428:web:dcf09b806cdad7599a20f9',
    messagingSenderId: '244411266428',
    projectId: 'pressdone-92fcb',
    authDomain: 'pressdone-92fcb.firebaseapp.com',
    storageBucket: 'pressdone-92fcb.firebasestorage.app',
    measurementId: 'G-325S7ZL8J4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFmu8phas-Sk-4VelGcaffn7-xmaJZ2LA',
    appId: '1:244411266428:android:5b2995d6b1b6aa229a20f9',
    messagingSenderId: '244411266428',
    projectId: 'pressdone-92fcb',
    storageBucket: 'pressdone-92fcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDANnCJUvG6dWClTiVP2vhAwkvIBUzmOe4',
    appId: '1:244411266428:ios:c8723a3ab9ece1f19a20f9',
    messagingSenderId: '244411266428',
    projectId: 'pressdone-92fcb',
    storageBucket: 'pressdone-92fcb.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDANnCJUvG6dWClTiVP2vhAwkvIBUzmOe4',
    appId: '1:244411266428:ios:c8723a3ab9ece1f19a20f9',
    messagingSenderId: '244411266428',
    projectId: 'pressdone-92fcb',
    storageBucket: 'pressdone-92fcb.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCawtle6G1fL_1gp8ohGwophie9oi_tWR8',
    appId: '1:244411266428:web:34495979b70832059a20f9',
    messagingSenderId: '244411266428',
    projectId: 'pressdone-92fcb',
    authDomain: 'pressdone-92fcb.firebaseapp.com',
    storageBucket: 'pressdone-92fcb.firebasestorage.app',
    measurementId: 'G-303WWKLCK9',
  );
}
